[server]
host = "0.0.0.0"
port = 9294

[upstream]
url = "https://rubygems.org"
timeout_secs = 30

[storage]
path = "./gems"

[database]
path = "./vein.db"

[logging]
level = "info"

[hotcache]
# Every minute for testing
refresh_schedule = "0 * * * * *"
