logger:
  enable: true
  pretty_backtrace: true
  level: debug
  format: compact

server:
  binding: {{ get_env(name="VEIN_ADMIN_BINDING", default="127.0.0.1") }}
  port: {{ get_env(name="VEIN_ADMIN_PORT", default="9400") }}
  host: {{ get_env(name="VEIN_ADMIN_HOST", default="127.0.0.1") }}
  ident: vein-admin
  middlewares:
    limit_payload:
      body_limit: 5mb
    timeout_request:
      enable: false

database:
  uri: {{ get_env(name="DATABASE_URL", default="sqlite://vein-admin.db?mode=rwc") }}
  enable_logging: false
  connect_timeout: 500
  idle_timeout: 500
  min_connections: 1
  max_connections: 1
  auto_migrate: true
  dangerously_truncate: false
  dangerously_recreate: false

workers:
  mode: BackgroundAsync

# Custom settings for Vein admin
settings:
  vein_config_path: {{ get_env(name="VEIN_CONFIG_PATH", default="vein.toml") }}
