logger:
  enable: true
  pretty_backtrace: true
  level: debug
  format: compact

server:
  binding: {{ get_env(name="VEIN_ADMIN_BINDING", default="127.0.0.1") }}
  port: {{ get_env(name="VEIN_ADMIN_PORT", default="9400") }}
  host: {{ get_env(name="VEIN_ADMIN_HOST", default="127.0.0.1") }}
  ident: vein-admin
  middlewares:
    limit_payload:
      body_limit: 5mb
    timeout_request:
      enable: false

workers:
  mode: BackgroundAsync

# Custom settings for Vein admin
settings:
  vein_config_path: {{ get_env(name="VEIN_CONFIG_PATH", default="vein.toml") }}
