logger:
  enable: true
  pretty_backtrace: false
  level: info
  format: json

server:
  binding: {{ get_env(name="VEIN_ADMIN_BINDING", default="0.0.0.0") }}
  port: {{ get_env(name="VEIN_ADMIN_PORT", default="9400") }}
  host: {{ get_env(name="VEIN_ADMIN_HOST", default="0.0.0.0") }}
  ident: vein-admin
  middlewares:
    limit_payload:
      body_limit: 5mb
    timeout_request:
      enable: true
      timeout: 30000

workers:
  mode: BackgroundAsync

# Custom settings for Vein admin
settings:
  vein_config_path: {{ get_env(name="VEIN_CONFIG_PATH", default="/etc/vein/vein.toml") }}
