logger:
  enable: false
  pretty_backtrace: true
  level: debug
  format: compact

server:
  binding: 127.0.0.1
  port: 0  # Random port for tests
  host: 127.0.0.1
  ident: vein-admin-test

workers:
  mode: BackgroundAsync

settings:
  vein_config_path: test_vein.toml
