[package]
name = "vein-admin"
version = "0.3.0"
edition = "2024"
license = "AGPL-3.0-only"
authors = ["Abdelkader Boudih <oss@seuros.com>"]
publish = false

[dependencies]
anyhow = "1.0.95"
async-trait = "0.1"
# note: rama has good server support included,
# but as you are using loco-rs you are bound to axum for now..
# however pretty certain you can ditch both loco-rs and axum and go with rama + something for your config
axum = "0.8.6"
chrono = { version = "0.4.38", default-features = false, features = ["clock"] }
clap = { version = "4.5.23", features = ["derive"] }
loco-rs = { version = "0.16.4", default-features = false, features = ["cli", "with-db"] }
tera = "1"
urlencoding = "2"
migration = { path = "migration" }
reqwest = { version = "0.12.24", default-features = false, features = ["rustls-tls"] }
sea-orm = "1.1.3"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
serde_yaml = "0.9"
tokio = { version = "1.43", features = ["rt-multi-thread", "macros", "signal"] }
tracing = "0.1.41"
vein = { path = "../.." }
vein-adapter = { path = "../vein-adapter" }

[dev-dependencies]
http-body-util = "0.1"
